/*
 * This file is generated by jOOQ.
 */
package com.jooq.data.tables.pojos;


import com.jooq.data.tables.interfaces.IStudent;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements IStudent {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;

    public Student() {}

    public Student(IStudent value) {
        this.id = value.getId();
        this.name = value.getName();
    }

    public Student(
        String id,
        String name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>school.student.id</code>. 学生id
     */
    @Override
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>school.student.id</code>. 学生id
     */
    @Override
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>school.student.name</code>. 学生姓名
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>school.student.name</code>. 学生姓名
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Student other = (Student) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStudent from) {
        setId(from.getId());
        setName(from.getName());
    }

    @Override
    public <E extends IStudent> E into(E into) {
        into.from(this);
        return into;
    }
}
