/*
 * This file is generated by jOOQ.
 */
package com.jooq.data.tables.pojos;


import com.jooq.data.tables.interfaces.ITeacherDetails;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherDetails implements ITeacherDetails {

    private static final long serialVersionUID = 1L;

    private Integer teacherId;
    private String address;
    private Integer salary;

    public TeacherDetails() {}

    public TeacherDetails(ITeacherDetails value) {
        this.teacherId = value.getTeacherId();
        this.address = value.getAddress();
        this.salary = value.getSalary();
    }

    public TeacherDetails(
        Integer teacherId,
        String address,
        Integer salary
    ) {
        this.teacherId = teacherId;
        this.address = address;
        this.salary = salary;
    }

    /**
     * Getter for <code>school.teacher_details.teacher_id</code>.
     */
    @Override
    public Integer getTeacherId() {
        return this.teacherId;
    }

    /**
     * Setter for <code>school.teacher_details.teacher_id</code>.
     */
    @Override
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * Getter for <code>school.teacher_details.address</code>.
     */
    @Override
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>school.teacher_details.address</code>.
     */
    @Override
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>school.teacher_details.salary</code>.
     */
    @Override
    public Integer getSalary() {
        return this.salary;
    }

    /**
     * Setter for <code>school.teacher_details.salary</code>.
     */
    @Override
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TeacherDetails other = (TeacherDetails) obj;
        if (this.teacherId == null) {
            if (other.teacherId != null)
                return false;
        }
        else if (!this.teacherId.equals(other.teacherId))
            return false;
        if (this.address == null) {
            if (other.address != null)
                return false;
        }
        else if (!this.address.equals(other.address))
            return false;
        if (this.salary == null) {
            if (other.salary != null)
                return false;
        }
        else if (!this.salary.equals(other.salary))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.teacherId == null) ? 0 : this.teacherId.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.salary == null) ? 0 : this.salary.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeacherDetails (");

        sb.append(teacherId);
        sb.append(", ").append(address);
        sb.append(", ").append(salary);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITeacherDetails from) {
        setTeacherId(from.getTeacherId());
        setAddress(from.getAddress());
        setSalary(from.getSalary());
    }

    @Override
    public <E extends ITeacherDetails> E into(E into) {
        into.from(this);
        return into;
    }
}
