/*
 * This file is generated by jOOQ.
 */
package com.jooq.data.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStudent extends Serializable {

    /**
     * Setter for <code>school.student.id</code>. 学生id
     */
    public void setId(String value);

    /**
     * Getter for <code>school.student.id</code>. 学生id
     */
    public String getId();

    /**
     * Setter for <code>school.student.name</code>. 学生姓名
     */
    public void setName(String value);

    /**
     * Getter for <code>school.student.name</code>. 学生姓名
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IStudent
     */
    public void from(IStudent from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IStudent
     */
    public <E extends IStudent> E into(E into);
}
