/*
 * This file is generated by jOOQ.
 */
package com.jooq.data.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITeacherDetails extends Serializable {

    /**
     * Setter for <code>school.teacher_details.teacher_id</code>.
     */
    public void setTeacherId(Integer value);

    /**
     * Getter for <code>school.teacher_details.teacher_id</code>.
     */
    public Integer getTeacherId();

    /**
     * Setter for <code>school.teacher_details.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>school.teacher_details.address</code>.
     */
    public String getAddress();

    /**
     * Setter for <code>school.teacher_details.salary</code>.
     */
    public void setSalary(Integer value);

    /**
     * Getter for <code>school.teacher_details.salary</code>.
     */
    public Integer getSalary();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITeacherDetails
     */
    public void from(ITeacherDetails from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITeacherDetails
     */
    public <E extends ITeacherDetails> E into(E into);
}
