/*
 * This file is generated by jOOQ.
 */
package com.jooq.data.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITeacher extends Serializable {

    /**
     * Setter for <code>school.teacher.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>school.teacher.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>school.teacher.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>school.teacher.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>school.teacher.age</code>.
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>school.teacher.age</code>.
     */
    public Integer getAge();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITeacher
     */
    public void from(ITeacher from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITeacher
     */
    public <E extends ITeacher> E into(E into);
}
