/*
 * This file is generated by jOOQ.
 */
package com.jooq.data;


import com.jooq.data.tables.Student;
import com.jooq.data.tables.Teacher;
import com.jooq.data.tables.TeacherDetails;
import com.jooq.data.tables.records.StudentRecord;
import com.jooq.data.tables.records.TeacherDetailsRecord;
import com.jooq.data.tables.records.TeacherRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * school.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, DSL.name("KEY_student_PRIMARY"), new TableField[] { Student.STUDENT.ID }, true);
    public static final UniqueKey<TeacherRecord> KEY_TEACHER_PRIMARY = Internal.createUniqueKey(Teacher.TEACHER, DSL.name("KEY_teacher_PRIMARY"), new TableField[] { Teacher.TEACHER.ID }, true);
    public static final UniqueKey<TeacherDetailsRecord> KEY_TEACHER_DETAILS_PRIMARY = Internal.createUniqueKey(TeacherDetails.TEACHER_DETAILS, DSL.name("KEY_teacher_details_PRIMARY"), new TableField[] { TeacherDetails.TEACHER_DETAILS.TEACHER_ID }, true);
}
