/*
 * This file is generated by jOOQ.
 */
package com.jooq.data;


import com.jooq.data.tables.Student;
import com.jooq.data.tables.Teacher;
import com.jooq.data.tables.TeacherDetails;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class School extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>school</code>
     */
    public static final School SCHOOL = new School();

    /**
     * The table <code>school.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>school.teacher</code>.
     */
    public final Teacher TEACHER = Teacher.TEACHER;

    /**
     * The table <code>school.teacher_details</code>.
     */
    public final TeacherDetails TEACHER_DETAILS = TeacherDetails.TEACHER_DETAILS;

    /**
     * No further instances allowed
     */
    private School() {
        super("school", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Student.STUDENT,
            Teacher.TEACHER,
            TeacherDetails.TEACHER_DETAILS
        );
    }
}
