/*
 * This file is generated by jOOQ.
 */
package com.jooq.data;


import com.jooq.data.tables.Student;
import com.jooq.data.tables.Teacher;
import com.jooq.data.tables.TeacherDetails;


/**
 * Convenience access to all tables in school.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>school.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>school.teacher</code>.
     */
    public static final Teacher TEACHER = Teacher.TEACHER;

    /**
     * The table <code>school.teacher_details</code>.
     */
    public static final TeacherDetails TEACHER_DETAILS = TeacherDetails.TEACHER_DETAILS;
}
